settings:
  every-join-is-first-join: false
on-first-join:
  delay-everything-below-by: 0
  fun-stuff:
    play-sound:
      enabled: true
      sound-name: entity_player_levelup
      listen-permission: firstjoinplus.notify
    smoke-effect:
      enabled: true
    launch-firework:
      enabled: false
  first-join-kit:
    enabled: true
    items:
    - wood_sword
    - wood_pickaxe
    - wood_spade
    - wood_axe
    - bread:5
  give-written-books:
    enabled: false
    book-files:
    - rules.txt
  give-experience:
    enabled: false
    level-amount: 0
  run-commands:
    enabled: false
    commands:
    - me just joined for the first time!
  run-console-commands:
    enabled: false
    commands:
    - setgroup %player_name newbies
  apply-potion-effects:
    enabled: true
    effects:
    - DAMAGE_RESISTANCE:100:600
  send-messages:
    enabled: false
    messages:
    - '&2Welcome to our server, %player_name!'
  reset-state:
    enabled: false